spring.application.name=parking-core
server.port=3003

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/parking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

## Resilience4j
resilience4j.retry.instances.api.max-attempts=3
resilience4j.retry.instances.api.wait-duration=5s
resilience4j.retry.instances.api.enableExponentialBackoff=true
resilience4j.retry.instances.api.exponentialBackoffMultiplier=2
resilience4j.retry.instances.api.retryExceptions[0]=java.lang.Exception

# API
simulator.url=http://localhost:3000